In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

In [5]:
#Q8: A

import pandas as pd

df_orders = pd.read_csv('../data/orders.csv')

cancelled_orders = df_orders[df_orders['order_status'] == 'cancelled']

payment_method_count = cancelled_orders['payment_method'].value_counts()

payment_method_count = payment_method_count.sort_values(ascending=False).reset_index()
payment_method_count.columns = ['Payment_method', 'Count']

print("Payment method count for cancelled orders:")
payment_method_count

Payment method count for cancelled orders:

  Payment_method  Count
0    credit_card  28452
1            cod  15468
2         paypal   7817
3      apple_pay   5190
4  bank_transfer   2535

In [7]:
#Q9: A

df_returns = pd.read_csv('../data/returns.csv')
df_products = pd.read_csv('../data/products.csv')
df_order_items = pd.read_csv('../data/order_items.csv', dtype={'promo_id_2': str})

order_items_size = pd.merge(
    df_order_items,
    df_products[['product_id', 'size']],
    on='product_id'
)

sales_count = order_items_size.groupby('size').size()

returns_size = pd.merge(
    df_returns, 
    df_products[['product_id', 'size']], 
    on='product_id')
returns_count = returns_size.groupby('size').size()

return_rate = (returns_count / sales_count).sort_values(ascending=False)

df_return_rates = pd.DataFrame({
    'Total_sales': sales_count,
    'Total_returns': returns_count,
    'Return_rate': returns_count / sales_count
}).sort_values('Return_rate', ascending=False)

df_return_rates

      Total_sales  Total_returns  Return_rate
size
S          172042           9723     0.056515
L          173174           9741     0.056250
M          176428           9820     0.055660
XL         193025          10655     0.055200

In [ ]:
#Q10: C

df_payments = pd.read_csv('../data/payments.csv')

payment_value = df_payments
avg_payment_by_installment = payment_value.groupby('installments')['payment_value'].mean()

df_results = avg_payment_by_installment.reset_index()
df_results.columns = ['Installments', 'Average Value']

df_results = df_results.sort_values(by = 'Average Value', ascending = True)

df_results

   Installments  Average Value
1             2     708.473729
0             1   24113.274166
4            12   24245.772694
2             3   24399.635486
3             6   24446.654403